apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-example
  namespace: dev
spec:
  rules:
    - host: "ingress-example.minikube"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clusterip
                port:
                 number: 80
